const app=document.querySelector('.phone');
if(document.body.classList.contains('orbit')){const link=document.querySelector('.skip');link.textContent='Dashboard';link.onclick=()=>location.href='orbit-dashboard.html'}
const flow=`
<section id="staffLogin" class="screen"><div class="auth-art"><span class="auth-glyph">↗</span></div><header class="auth-head"><button class="back" data-go="welcome">← Back</button><h1>Welcome back</h1><p>Log in to run today’s floor.</p></header><form class="form"><div class="field"><label>Email</label><input type="email" placeholder="rahul@ironhouse.in"></div><div class="field"><label>Password</label><input type="password" placeholder="••••••••"></div><button class="forgot" data-go="forgot">Forgot password?</button><button class="btn">Log in</button><div class="divider">OR</div><button class="btn outline">G&nbsp;&nbsp; Continue with Google</button><p class="switch">New gym? <button data-go="staffSignup">Create an account</button></p></form></section>
<section id="staffSignup" class="screen"><header class="auth-head"><button class="back" data-go="staffLogin">← Back</button><h1>Create your gym</h1><p>Start with the owner account.</p></header><form class="form"><div class="split"><div class="field"><label>Gym name</label><input placeholder="FitZone Gym"></div><div class="field"><label>Your name</label><input placeholder="Rahul"></div></div><div class="field"><label>Country & currency</label><select><option>India · INR</option></select></div><div class="field"><label>Email</label><input type="email" placeholder="rahul@ironhouse.in"></div><div class="split"><div class="field"><label>Mobile (optional)</label><input placeholder="9876543210"></div><div class="field"><label>Password</label><input type="password" placeholder="8+ characters"></div></div><label class="legal"><input type="checkbox"> <span>I agree to the Terms and Privacy Policy.</span></label><button class="btn" data-go="ownerOtp">Create my gym</button></form></section>
<section id="ownerOtp" class="screen"><div class="auth-art"><span class="auth-glyph">✉</span></div><header class="auth-head"><button class="back" data-go="staffSignup">← Back</button><h1>Check your email</h1><p>Enter the six-digit code sent to your inbox.</p></header><form class="form"><div class="field"><label>Verification code</label><input class="code" maxlength="6" placeholder="000000"></div><button class="btn">Verify account</button><p class="switch">No code? <button>Send again</button></p></form></section>
<section id="forgot" class="screen"><div class="auth-art"><span class="auth-glyph">↺</span></div><header class="auth-head"><button class="back" data-go="staffLogin">← Back</button><h1>Reset password</h1><p>We’ll send a secure reset link to your email.</p></header><form class="form"><div class="field"><label>Email</label><input type="email" placeholder="rahul@ironhouse.in"></div><button class="btn">Send reset link</button></form></section>
<section id="memberLogin" class="screen"><div class="auth-art"><span class="auth-glyph">✓</span></div><header class="auth-head"><button class="back" data-go="welcome">← Back</button><h1>Member login</h1><p>Use the mobile number your gym has on file.</p></header><form class="form"><div class="field"><label>Mobile number</label><input inputmode="tel" placeholder="9876543210"></div><div class="field"><label>Password</label><input type="password" placeholder="••••••"></div><button class="forgot" data-go="memberHelp">Forgot password?</button><button class="btn">Log in</button><p class="switch">First time? <button data-go="memberSignup">Activate your account</button></p></form></section>
<section id="memberSignup" class="screen"><div class="steps"><i class="on"></i><i></i><i></i><i></i></div><header class="auth-head"><button class="back" data-go="memberLogin">← Back</button><h1>Find your gym</h1><p>Enter the six-digit code from your front desk.</p></header><form class="form"><div class="field"><label>Gym code</label><input class="code" inputmode="numeric" maxlength="6" placeholder="123456"></div><button class="btn">Continue</button><div class="info">Next you’ll verify your mobile number by SMS, then create your password.</div></form></section>
<section id="memberHelp" class="screen"><div class="pad"><button class="back" data-go="memberLogin">← Back</button><div class="done">↺</div><h1 class="title">Reset over SMS</h1><p class="copy">Confirm your gym and registered mobile number, then choose a new password.</p><div class="info"><b>1.</b> Enter gym code<br><b>2.</b> Verify mobile by SMS<br><b>3.</b> Set new password</div><div class="actions"><button class="btn" data-go="memberSignup">Reset my password</button><button class="btn light" data-go="memberLogin">Back to login</button></div></div></section>`;
app.insertAdjacentHTML('beforeend',flow);
document.querySelectorAll('form').forEach(f=>f.addEventListener('submit',e=>e.preventDefault()));
document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(!b)return;e.preventDefault();document.querySelector('.screen.active')?.classList.remove('active');document.getElementById(b.dataset.go)?.classList.add('active');});
